This notebook regroups the code sample of the video below, which is a part of the [Hugging Face course](https://huggingface.co/course).

In [ ]:
#@title
from IPython.display import HTML

HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/Dh9CL8fyG80?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>')

Install the Transformers and Datasets libraries to run this notebook.

In [1]:
! pip install datasets transformers[sentencepiece]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 6.8 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


In [4]:
from datasets import load_dataset
# AutoTokenizer: класс из transformers, автоматически подбирающий токенизатор для указанной модели.
# DataCollatorWithPadding: класс, который автоматически дополняет входные данные до одной длины, чтобы можно было эффективно обрабатывать их батчами.
from transformers import AutoTokenizer, DataCollatorWithPadding

raw_datasets = load_dataset("glue", "mrpc")


In [7]:
# Загружается набор данных GLUE, поднабор MRPC (Microsoft Research Paraphrase Corpus).
# MRPC — это задача определения, являются ли две строки перефразировкой друг друга (классификация бинарных меток).
# Возвращаемый объект — словарь с разделением на train, validation, и (иногда) test части.
# {
#   'train': Dataset({
#       'sentence1': [...],  # Первая строка
#       'sentence2': [...],  # Вторая строка
#       'label': [...],      # Метки (0 или 1)
#       'idx': [...]         # Индексы записей
#   }),
#   'validation': ...,
#   'test': ...
# }

raw_datasets

DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 408
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 1725
    })
})

In [8]:
# checkpoint: определяет конкретную предобученную модель. Здесь используется модель bert-base-cased, которая учитывает регистр букв.
# AutoTokenizer.from_pretrained(checkpoint): загружает токенизатор, соответствующий указанной модели (в данном случае BERT). Этот токенизатор превращает текст в числовые представления (токены), которые могут быть поданы в модель.

checkpoint = "bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [9]:
# Функция принимает на вход батч примеров (например, из датасета).
# Она токенизирует два текстовых поля (sentence1 и sentence2) одновременно, обрезая их до максимальной длины, допустимой для модели (truncation=True).
# Возвращает результат токенизации в виде словаря, содержащего токены (input_ids, attention_mask и, при необходимости, token_type_ids).

def tokenize_function(examples):
    return tokenizer(examples["sentence1"], examples["sentence2"], truncation=True)

# raw_datasets.map: применяет функцию токенизации к каждому элементу датасета.
# batched=True: функция применяется к батчам данных, а не к отдельным строкам, что ускоряет обработку.
# После этого tokenized_datasets содержит токенизированные данные.
tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)
tokenized_datasets

Map:   0%|          | 0/1725 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 408
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 1725
    })
})

In [14]:
tokenized_datasets['train']["sentence1"][:5]

['Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
 "Yucaipa owned Dominick 's before selling the chain to Safeway in 1998 for $ 2.5 billion .",
 'They had published an advertisement on the Internet on June 10 , offering the cargo for sale , he added .',
 'Around 0335 GMT , Tab shares were up 19 cents , or 4.4 % , at A $ 4.56 , having earlier set a record high of A $ 4.57 .',
 'The stock rose $ 2.11 , or about 11 percent , to close Friday at $ 21.51 on the New York Stock Exchange .']

In [15]:
tokenized_datasets['train']["sentence2"][:5]

['Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .',
 "Yucaipa bought Dominick 's in 1995 for $ 693 million and sold it to Safeway for $ 1.8 billion in 1998 .",
 "On June 10 , the ship 's owners had published an advertisement on the Internet , offering the explosives for sale .",
 'Tab shares jumped 20 cents , or 4.6 % , to set a record closing high at A $ 4.57 .',
 'PG & E Corp. shares jumped $ 1.63 or 8 percent to $ 21.03 on the New York Stock Exchange on Friday .']

In [16]:
tokenized_datasets['train']["label"][:5]

[1, 0, 1, 0, 1]

In [17]:
tokenized_datasets['train']["idx"][:5]

[0, 1, 2, 3, 4]

In [18]:
# Удаляются столбцы, которые больше не нужны (sentence1, sentence2, и idx), так как вместо них теперь есть токенизированные данные.
tokenized_datasets = tokenized_datasets.remove_columns(["sentence1", "sentence2", "idx"])
# Столбец label переименовывается в labels, чтобы привести его к стандартному названию, ожидаемому большинством моделей из библиотеки transformers.
tokenized_datasets = tokenized_datasets.rename_column("label", "labels")
# Преобразует токенизированный датасет в формат, поддерживаемый PyTorch. Например, столбцы будут преобразованы в torch.Tensor
tokenized_datasets.set_format("torch")

tokenized_datasets

DatasetDict({
    train: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 408
    })
    test: Dataset({
        features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 1725
    })
})

In [22]:
tokenizer

BertTokenizerFast(name_or_path='bert-base-cased', vocab_size=28996, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [23]:
# DataCollatorWithPadding автоматически добавляет padding (заполнение) к токенам в батче, чтобы длина всех примеров в батче была одинаковой.
# Это полезно для работы с переменной длиной предложений в датасетах. Padding добавляется только до необходимой длины, что эффективно при обучении.
data_collator = DataCollatorWithPadding(tokenizer)

In [31]:
# DataLoader — компонент PyTorch, который позволяет итерировать по данным батчами, добавляя поддержку шифрования (shuffling), параллельной загрузки и других удобств.
# Основное использование DataLoader — для подготовки данных к передаче в модель во время обучения и оценки.
from torch.utils.data import DataLoader

# tokenized_datasets["train"]:
# Подразумевается, что tokenized_datasets — это токенизированный датасет, созданный ранее.
# Здесь выбирается тренировочная часть датасета ("train").
# shuffle=True:

# Перемешивает данные в начале каждой эпохи.
# Это полезно для обучения, чтобы модель не видела данные в одном и том же порядке на каждой итерации.
# batch_size=8:

# Размер батча — количество примеров, которые обрабатываются одновременно на одной итерации.
# Здесь устанавливается, что батч содержит 8 примеров.
# collate_fn=data_collator:

# Указывает функцию, которая собирает батч данных.
# В данном случае используется DataCollatorWithPadding, который автоматически выравнивает длину токенов в батче (добавляет padding).
train_dataloader = DataLoader(
  tokenized_datasets["train"], shuffle=True, batch_size=8, collate_fn=data_collator
)

# shuffle=False:
# Здесь опция shuffle не указана, а значит по умолчанию стоит False.
# Перемешивание для валидационных данных не требуется, так как они используются для оценки, а порядок данных может быть важен для реплицируемости экспериментов.
eval_dataloader = DataLoader(
  tokenized_datasets["validation"], batch_size=8, collate_fn=data_collator
)

In [29]:
tokenized_datasets["train"]['input_ids'][:5]

[tensor([  101,  7277,  2180,  5303,  4806,  1117,  1711,   117,  2292,  1119,
          1270,   107,  1103,  7737,   107,   117,  1104,  9938,  4267, 12223,
         21811,  1117,  2554,   119,   102, 11336,  6732,  3384,  1106,  1140,
          1112,  1178,   107,  1103,  7737,   107,   117,  7277,  2180,  5303,
          4806,  1117,  1711,  1104,  9938,  4267, 12223, 21811,  1117,  2554,
           119,   102]),
 tensor([  101, 10684,  2599,  9717,  1161,  2205, 11288,  1377,   112,   188,
          1196,  4147,  1103,  4129,  1106, 19770,  2787,  1107,  1772,  1111,
           109,   123,   119,   126,  3775,   119,   102, 10684,  2599,  9717,
          1161,  3306, 11288,  1377,   112,   188,  1107,  1876,  1111,   109,
          5691,  1495,  1550,  1105,  1962,  1122,  1106, 19770,  2787,  1111,
           109,   122,   119,   129,  3775,  1107,  1772,   119,   102]),
 tensor([  101,  1220,  1125,  1502,  1126, 16355,  1113,  1103,  4639,  1113,
          1340,  1275,   117,  4

In [32]:
tokenized_datasets["train"]['token_type_ids'][:5]

[tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])]

In [33]:
# Возвращаемый объект batch содержит:
# input_ids: токены входных данных.
# attention_mask: маски, указывающие на важные токены (без учета padding).
# labels: метки классов.

# token_type_ids
# В большинстве моделей на базе BERT (например, bert-base-uncased), если у вас есть два предложения, то:
# Все токены первого предложения получают значение 0.
# Все токены второго предложения получают значение 1

# attention_mask:
# Назначение: Это маска, которая указывает, какие токены следует учитывать при вычислении внимания в модели. Важно для работы с переменной длиной последовательности и padding'ом.
# 1 в маске означает, что токен следует учитывать при вычислении внимания.
# 0 в маске означает, что токен — это padding (заполнитель), и его не нужно учитывать.
for batch in train_dataloader:
    break
print({k: v.shape for k, v in batch.items()})

{'labels': torch.Size([8]), 'input_ids': torch.Size([8, 77]), 'token_type_ids': torch.Size([8, 77]), 'attention_mask': torch.Size([8, 77])}


In [35]:
# AutoModelForSequenceClassification — это класс из библиотеки transformers, предназначенный для загрузки предобученной модели для задачи классификации текста (например, бинарной классификации или многоклассовой классификации).
# Класс автоматически выбирает правильную модель для классификации на основе заданного имени модели (или контрольной точки, как в примере)
from transformers import AutoModelForSequenceClassification

# checkpoint — это строка, которая указывает на предобученную модель, которую вы хотите использовать. В данном случае используется bert-base-cased:
# bert-base-cased — это версия модели BERT с 12 слоями, обученная на корпусе текста, где учитывается регистр букв (например, "Apple" и "apple" будут трактоваться по-разному).
checkpoint = "bert-base-cased"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
outputs = model(**batch)
print(outputs.loss, outputs.logits.shape)

tensor(0.7512, grad_fn=<NllLossBackward>) torch.Size([8, 2])


In [ ]:
from transformers import AdamW

optimizer = AdamW(model.parameters(), lr=5e-5)

In [ ]:
loss = outputs.loss
loss.backward()
optimizer.step()

# Don't forget to zero your gradients once your optimizer step is done!
optimizer.zero_grad()

In [ ]:
from transformers import get_scheduler

num_epochs = 3
num_training_steps = num_epochs * len(train_dataloader)
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps
)

In [ ]:
import torch

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
model.to(device)
print(device)

cuda


In [ ]:
optimizer = AdamW(model.parameters(), lr=5e-5)

In [ ]:
from tqdm.auto import tqdm

progress_bar = tqdm(range(num_training_steps))

model.train()
for epoch in range(num_epochs):
    for batch in train_dataloader:
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)
        loss = outputs.loss
        loss.backward()

        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

In [ ]:
from datasets import load_metric

metric= load_metric("glue", "mrpc")
model.eval()
for batch in eval_dataloader:
    batch = {k: v.to(device) for k, v in batch.items()}
    with torch.no_grad():
        outputs = model(**batch)

    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)
    metric.add_batch(predictions=predictions, references=batch["labels"])

metric.compute()

{'accuracy': 0.8284313725490197, 'f1': 0.8809523809523808}